### PR TITLE
Add a test for concurrent write protection

### PR DESCRIPTION
**Pull request by ezzatron**
This is my attempt at demonstrating the effects of Postgres' implicit locking on concurrent event append operations.

The test added in this PR uses two separate Postgres clients. It might be a bit cryptic to read, but essentially boils down to this scenario:

- Client A starts a transaction
- Client B starts a transaction
- Client A starts appending event A at offset 0, acquiring an implicit lock
- Client B starts appending event B at offset 0, but must wait for the lock acquired by Client A to be released
- Client A finishes appending event A
- Client A appends event C at offset 1, using its existing lock
- Client A commits its transaction, releasing the lock
- Client B's append fails since the offset it originally specified is already written
- Client B rolls back its transaction

The upshot for each client is:
- Client A gets exactly what it wants
- Client B has to wait for Client A to finish its work before it knows that its own operation failed

### CODE REVIEW

**Comment by ezzatron** [comment]
@jmalloc What do you think of this test? It's an attempt to demonstrate how Postgres' table-level locks protect event streams from concurrent writes.

**Comment by jmalloc** [comment]
I'd probably want to assert on the contents of the event table in the end, not just the log, but the logic seems right (although a little cryptic as you say, for me mostly around the use of the "guards" that synchronise between the beginning of A / B).

**Comment by ezzatron** [comment]
@jmalloc I've re-written the test, and I think it's much clearer now. There's also some test comments which should help.

The only thing that is potentially "weaker" about this version of the test is that client B now waits for client A's first append to completely finish before starting its own, rather than starting them as close together as possible. I don't think it's really a big deal, because the test still shows a situation where a deadlock would occur if two operations were *not* run in parallel.

**Comment by jmalloc** [comment]
Much better imo, and marginally more robust as well.

**Comment by ezzatron** [comment]
Nice 👍

**Pull request merged**
